### ISSUE TITLE
Lab1-5: Fix person fields to contain a First and a Last name

### ISSUE THREAD

**Issue by kmfarley11** [kmfarley11/EECE4040_2015FS#10]
"the key is the person’s name (when comparing keys first compare last names; then if last names are the same compare first names"

The Person class was previously implemented with merely a Name field: there needs to be two names and the insert, delete, and searching algorithms must re-account for this.

**Comment by kmfarley11** [comment]
Fixed in pull request #11 .

**Comment by okeltw** [comment]
SHUT UP KEVIN. <3
