### ISSUE TITLE
Lab2-0 Create Class Digraph

### ISSUE THREAD

**Issue by kmfarley11** [kmfarley11/EECE4040_2015FS#13]
"This program involves implementing an ADT Directed Graph and performing a
topological sort, acyclic check, and strong connectivity check for the directed graph. You
are to implement the directed graph using pointer-based adjacency lists."

We essentially need to create a class which contains a list of header nodes (or an array of header data), then edge nodes for the header items. The operations will be a variety of methods needed to operate on adjacency lists.

**Comment by kmfarley11** [comment]
Pull requested on "Lab2-0: Create Class Digraph #19 "

**Comment by okeltw** [comment]
Looks good to me.
