### ISSUE TITLE
Lab2-3 Implement Acyclic Check

### ISSUE THREAD

**Issue by kmfarley11** [kmfarley11/EECE4040_2015FS#16]
"...topological sorting and acyclic check. You are to implement the topological sorting operation using topSort2 (see pages 616-618 of Carano text)"

This issue will require some research on what the check is and how to implement it.

**Comment by kmfarley11** [comment]
This issue may be kind-of tricky because it bleeds into both the AddEdge and TopologicalSort modules. I won't assign it to myself until more information is obtained / discussed

**Comment by okeltw** [comment]
When do you want to discuss it then?

I'll work on my issue as soon as possible - which issues are the dependencies for the sort?

**Comment by kmfarley11** [comment]
Not sure either tomorrow or Monday. I still need to do a little bit of research on it. It looks as though the acyclic check may be more tied to the Add Edge because I don't think a user should be able to add an edge if it creates a cycle.

I will do some research and get back to you by Monday.

**Comment by kmfarley11** [comment]
I believe this still needs to be a independent issue. There is no need for anybody to wait for this to be completed before working on their parts. If any of your code touches mine: just force it to return whatever value you need.

**Comment by kmfarley11** [comment]
didn't mean to close it ;)

**Comment by kmfarley11** [comment]
Merged into master with pull request: Lab2-3 Create Logic for AcyclicCheck #25. Won't close the issue until the project is turned in.
