### ISSUE TITLE
Lab3-2: Private Key Generation

### ISSUE THREAD

**Issue by kmfarley11** [kmfarley11/EECE4040_2015FS#30]
"Extended Euclid GCD"

This issue should generate a private key given a public key as well as other internals (the totient / modulus). Note: There are a lot of implementations of the extended euclid GCD online. This issue will require some research as well as coding. Not sure how to test this code, if googletest can be used then great, otherwise just run some print statements or something.

Use this for reference: https://en.wikipedia.org/wiki/RSA_(cryptosystem)

**Comment by okeltw** [comment]
I changed the ExtendedEuclidean function to
void ExtendedEuclidean(int a, int b, int &g, int &s, int &t);

g is the new gcd(a,b), updated by-reference.  This will allow me to write this recursively.

**Comment by okeltw** [comment]
Getting an error from within google test:

tester.cpp: In member function 'virtual void Cryptosystem_ExtendedEuclidean_ReturnsExpected_Test::TestBody()':
tester.cpp:77:2: error: expected ';' before 'switch'
  EXPECT_TRUE(g > 0);
  ^
In file included from ../gtest/include/gtest/gtest.h:58:0,
                 from tester.cpp:16:
tester.cpp:77:2: error: 'else' without a previous 'if'
  EXPECT_TRUE(g > 0);
  ^
tester.cpp:77:2: error: 'gtest_ar_' was not declared in this scope
  EXPECT_TRUE(g > 0);
  ^

I don't know what to do with this.
